inherit_from: .rubocop_todo.yml

require: rubocop-performance

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - '**/*~'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/golden_rules_test.rb'
