inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - '**/*~'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/srx/golden_rules_test.rb'
